name: Daily srs merge

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    permissions:
        contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mkdir
        run: |
          mkdir -p temp srs

      - name: Install sing-box
        run: |
          curl -fsSL https://raw.githubusercontent.com/SagerNet/sing-box/main/install.sh | bash -s -- -y

- name: Run Merge Script
  run: bash srs/merge-srs.sh


      - name: Run merge script
        run: bash srs/merge-srs.sh

      - name: Commit and push srs if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Daily srs merge"
          file_pattern: "srs/*.srs"
